config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'

devise_for :users

  get "home/about" => "home#about"
  root 'users#show'

  resources :books, only: [:create, :index, :edit, :update, :show, :destroy]

  resources :users, only: [:show, :create, :index, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
  	validates :body, presence: true,
  					 length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true,
  				   length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  	private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
  def after_sign_in_path_for(resource)
  	user_path(current_user.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :correct_book, only: [:edit, :update]
	def create
	 @book = Book.new(book_params)
	 @book.user_id = current_user.id
	
	if @book.save
	   flash[:notice] = "Book was successfully created."
	   redirect_to book_path(@book.id)
	   
	else
	  @books = Book.all
	  render :index
	end
	end

	def index
	 @book = Book.new
  	 @books = Book.all
	end

	def edit
  	@book = Book.find(params[:id])
  	end

  	def  update
	@book = Book.find(params[:id])
	 if @book.update(book_params)
	 	flash[:notice] = "You have updated book successfully."
		redirect_to book_path(@book.id)
		
	 else
      render :edit
     end
  	end

	def show
	 @book = Book.find(params[:id])
	 @book_new = Book.new
	end

	def destroy
  	 @book = Book.find(params[:id])
  	 @book.destroy
  	 redirect_to books_path
	end

private
  	def book_params
  	 params.require(:book).permit(:title, :body)
  	end

  	def correct_book
    book = Book.find(params[:id])
    if current_user.id != book.user_id
      redirect_to books_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def top
end
def about
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :correct_user, only: [:edit, :update]
  def show
  	@user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def create
    @users = User.new(user_params)
    @users.user_id = current_user.id
    @user.save
    flash[:notice] = "Welcome! You have signed up successfully."
    redirect_to user_path
  end

  def index
    @user = User.new
    @users = User.all
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
   else
      render :edit
    end
  end

   private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  def book_params
    params.require(:book).permit(:title,:body)
  end

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
	
<% end %>
<h2>Editing Book</h2>
<% if @book.errors.any? %>
	<%= @book.errors.count %>errors prohibited this book from being saved:<br>
	<% @book.errors.full_messages.each do |msg| %>
	<%= msg %>
	<% end %>
<% end %>
	<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>

		<h4>title</h4>
		<%= f.text_field :title %>
		
		<h4>body</h4>
		<%= f.text_area :body %>
		<br><%= f.submit 'Update Book' %>
	
	<% end %>
	<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
 	 <div class="col-xs-3">
 	 	<h2>User info</h2>
 	 	<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
 	 	<table class="table table-striped">
 	 		<tbody>
 	 			<tr></tr>
 	 			<tr>
 	 			  <th>name</th>
 	 			  <th><%= current_user.name %></th>
 	 			</tr>
 	 			<tr>
  	 			  <th>introduction</th>
 	 			  <th><%= current_user.introduction %></th>
 	 			</tr>
 	 		</tbody>
 	 	</table>

          <%= link_to "", edit_user_path(current_user), class: "btn btn-default col-xs-12 glyphicon glyphicon-wrench", aria: {hidden: true} %>

   	   <h2>New book</h2>
   	
    <%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:<br>
        <% @book.errors.full_messages.each do |msg| %>
        <%= msg %><br>
        <% end %>
      <% end %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      <br><%= f.submit 'Create Book' %>
    <% end %>
	</div>

  <div class="col-xs-9">
	<h2>Books</h2>
    	<table class="table table-striped">
    		<thead>
    			<tr>
    				<th></th>
    				<th>Title</th>
    				<th>Opinion</th>
    			</tr>
    		</thead>
			<% @books.each do |book| %>
    		<tbody>
    			<tr>
    				<td><%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
              <% end %>
            </td>
    				<td><%= link_to book.title, book_path(book.id) %></td>
					 <td><%= book.body %></td>
    			</tr>
    		</tbody>
    		<% end %>
    	</table>
    </div>
  </div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
 	 <div class="col-xs-3">
      <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
 	 	<h2>User info</h2>
 	 	<%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg"%>
 	 	<table class="table table-striped">
 	 		<tbody>
 	 			<tr></tr>
 	 			<tr>
 	 			  <th>name</th>
 	 			  <th><%= @book.user.name %></th>
 	 			</tr>
 	 			<tr>
  	 			  <th>introduction</th>
 	 			  <th><%= @book.user.introduction %></th>
 	 			</tr>
 	 		</tbody>
 	 	</table>
          <%= link_to "", edit_user_path(current_user), class: "btn btn-default col-xs-12 glyphicon glyphicon-wrench", aria: {hidden: true} %>
   	   <h2>New book</h2>
   	
    <%= form_for(@book_new) do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      <br><%= f.submit 'Create Book' %>
    <% end %>
	</div>

  <div class="col-xs-9">
	<h2>Book detail</h2>
    	<table class="table table-striped">
    		<tbody>
    			<tr>
    				<td><%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
              <br><%= current_user.name %>
              <% end %>
              </td>
    				<td><%= link_to @book.title, book_path %></td>
					<td><%= @book.body %></td>
					<td><% if @book.user == current_user %>
 						<%= link_to "Edit", edit_book_path(@book.id) %><% end %>
 					</td>
					<td><% if @book.user == current_user %>
 						<%= link_to "Destroy", book_path(@book), method: :delete %><% end %>
 					</td>
    			</tr>
    		</tbody>
    	</table>
    </div>
  </div>

app/views/home/about.html.erb
<div class="container">
	<div class="row">
 	 <div class="col text-center">

 	 	<h2>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h2>

	 </div>

 	 </div>
	</div>

app/views/home/top.html.erb
<div class="container">
	<div class="row">
 	 <div class='col-xs-6 col-xs-offset-3' >
 	  
 	  <% if flash[:notice] %>
       <div class="flash">
        <%= flash[:notice] %>
       </div>
      <% end %>
 	 	
 	 	<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
 	 	<div class="text-left">In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,<br>
			you can share and exchange your opinions , inpressions , and emotions<br>
	 		about various books!</div>
	 	<div class="row">
	 		<%= link_to "Log in", new_user_session_path, class: 'btn btn-info col-xs-12' %>
	    </div>
	 	<div class="row">
	 		<%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success col-xs-12' %>
	 	</div>
	 </div>

 	 
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersLevel2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header" id="header">
      <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 class="navbar-brand" >Bookers</h3>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li class="active">
        <span class="glyphicon glyphicon-home" aria-hidden="true"><%= link_to "Home", user_path(current_user.id) %></span></li>
      <li>
        <span class="glyphicon glyphicon-link" aria-hidden="true"><%= link_to 'Users', users_path %></span></li>
      <li>
        <span class="glyphicon glyphicon-edit" aria-hidden="true"><%= link_to "Books", books_path %></span></li>
      <li>
        <span class="glyphicon glyphicon-log-in" aria-hidden="true"><%= link_to "logout", destroy_user_session_path, method: :delete %></span></li>
      <% else %>
      <li class="active">
        <span class="glyphicon glyphicon-home" aria-hidden="true"><%= link_to " Home", root_path %></span></li>
      <li>
        <span class="glyphicon glyphicon-link" aria-hidden="true"><%= link_to ' About', home_about_path %></span></li>
      <li>
        <span class="glyphicon glyphicon-edit" aria-hidden="true"><%= link_to " sign up", new_user_registration_path %></span></li>
      <li>
        <span class="glyphicon glyphicon-log-in" aria-hidden="true"><%= link_to " login", new_user_session_path %></span></li>
      <% end %>
    </ul>
  </div>
 </nav>


</footer>

    <%= yield %>

    </div>
 <div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-9">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
 </div>
  <!-- Copyright -->
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
 	 <div class="col-xs-3">
 	 	<h2>User info</h2>
 	 	<% if @user.errors.any? %>
			<%= @user.errors.count %>errors prohibited this user from being saved:<br>
			<% @user.errors.full_messages.each do |msg| %>
			<%= msg %>
			<% end %>
		<% end %>
		<%= form_for(@user, url:"/users/#{@user.id}") do |f| %>

		 <h4>Name</h4>
          <%= f.text_field :name %>
         <h4>Image</h4>
          <%= f.attachment_field :profile_image %>
         <h4>Introduction</h4>
      	  <%= f.text_area :introduction %>
          <%= f.submit "Update User" %>
        <% end %>


	 </div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
 	 <div class="col-xs-3">
 	 	<h2>User info</h2>
 	 	<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg"%>
 	 	<table class="table table-striped">
 	 		<tbody>
 	 			<tr></tr>
 	 			<tr>
 	 			  <th>name</th>
 	 			  <th><%= current_user.name %></th>
 	 			</tr>
 	 			<tr>
  	 			  <th>introduction</th>
 	 			  <th><%= current_user.introduction %></th>
 	 			</tr>
 	 		</tbody>
 	 	</table>
          <%= link_to "", edit_user_path(current_user), class: "btn btn-default col-xs-12 glyphicon glyphicon-wrench", aria: {hidden: true} %>
   	   <h2>New book</h2>

    <%= form_for(@book) do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      <br><%= f.submit 'Create Book' %>
    <% end %>
	</div>

    <div class="col-xs-9">
	<h2>Users</h2>
    	<table class="table table-striped">
    		<thead>
    			<tr>
    				<th>image</th>
    				<th>name</th>
    				<th></th>
    			</tr>
    		</thead>
			<% @users.each do |user| %>
    		<tbody>
    			<tr>
    				<td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%></td>
    				<td><%= user.name %></td>
					<td><%= link_to "Show", user_path(user.id) %></td>
    			</tr>
    		</tbody>
    		<% end %>
    	</table>
    </div>
  </div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
 	 <div class="col-xs-3">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
 	 	<h2>User info</h2>

 	 	<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
 	 	<table class="table table-striped">
 	 		<tbody>
 	 			<tr></tr>
 	 			<tr>
 	 			  <th>name</th>
 	 			  <th><%= @user.name %></th>
 	 			</tr>
 	 			<tr>
  	 			  <th>introduction</th>
 	 			  <th><%= @user.introduction %></th>
 	 			</tr>
 	 		</tbody>
 	 	</table>

   	   		<%= link_to "", edit_user_path(current_user), class: "btn btn-default col-xs-12 glyphicon glyphicon-wrench", aria: {hidden: true} %>
   	    
   	   <h2>New book</h2>
   	
    <%= form_for(@book) do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      <br><%= f.submit 'Create Book' %>
    <% end %>
	</div>

<div class="col-xs-9">
	<h2>Books</h2>
    	<table class="table table-striped">
    		<thead>
    			<tr>
    				<th></th>
    				<th>Title</th>
    				<th>Opinion</th>
    			</tr>
    		</thead>
			  <% @books.each do |book| %>
    		<tbody>
    			<tr>
    				<td><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%></td>
    				<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
    			</tr>
    		</tbody>
    		<% end %>
    	</table>
    </div>
    </div>
  </div>